### ISSUE TITLE
Images not being saved on Windows

### ISSUE THREAD

**Issue by riensach** [dend/foggycam#18] opened 2018-07-25 12:03 UTC
Hello
Setup and installed fine. It finds the camera etc. But then it just repeats "applied cache buster" over and over. The folders are created to record images/video, but none make their way there.

![image](https://user-images.githubusercontent.com/11135516/43199712-d14fc800-900a-11e8-9b55-d162442eba0f.png)

**Comment by CormacAsGaeilge** [comment] 2018-08-09 11:15
I'm getting this same output

**Comment by CormacAsGaeilge** [comment] 2018-08-17 16:53
@riensach, I have found the cause of the issue. I am in Europe and this code is directing the http calls to the us Nest API. In the foggycam.py file change the url to

nest_image_url = 'https://nexusapi-eu1.camera.home.nest.com/get_image?uuid=#CAMERAID#&width=#WIDTH#&cachebuster=#CBUSTER#'

This is for Europe. If you don't live in Europe or it just isn't working, go to your nest account and inspect  element your nest camera feed. View Source in the Chrome Debugger and make sure the url you are using matches the nexusapi url displayed.

**Comment by riensach** [comment] 2018-10-07 13:52
Thanks - solved it! Now have you managed to get ffmpeg working on windows?

**Comment by dend** [comment] 2018-11-29 07:44
This is a duplicate of #25 - thanks for the pointer, @CormacAsGaeilge!

@riensach @CormacAsGaeilge - please open a separate issue if you can't get `ffmpeg` working on Windows.

**Closed** 2018-11-29 07:44 UTC
